### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by ilu33** [xwiki-labs/cryptpad#252]
Upon registration the user needs to not only consent to the servers TOS but also acknowledge (that's enough, no consent needed) the servers data protection declaration. Even if cryptpad usage is anonymous, there's probably still personal data being collected (f.e. IPs in server logs). Also a little information doesn't do any harm.

The consent required for opt in to "some very basic feedback to the server" needs to be an informed consent so a list is needed what exactly that basic feedback is.
Also "to improve your experience" sounds like an advertizing buzzword which sounds suspicious to me (might be just me) so a little more detail would be good no matter what GDPR says. 

The information is mostly already there in out.policy_* but has to be linked at the correct places.
An additional section "out.policy_whatwestoreandhowlong" is needed.

**Comment by ansuz** [comment]
Hi,

> Even if cryptpad usage is anonymous, there's probably still personal data being collected (f.e. IPs in server logs). Also a little information doesn't do any harm.

Our privacy policy is displayed here: https://cryptpad.fr/privacy.html. We also wrote a blog post about exactly which information we are able to access. https://blog.cryptpad.fr/2017/07/07/cryptpad-analytics-what-we-cant-know-what-we-must-know-what-we-want-to-know/

> Also "to improve your experience" sounds like an advertizing buzzword which sounds suspicious to me

We use it to determine which browser APIs are supported by our clients, such as our recently deployed [worker infrastructure](https://blog.cryptpad.fr/2018/06/22/Faster-loads-with-SharedWorker-ServiceWorker/), as well as to determine what our users' screen dimensions are. These statistics have helped us to provide better support for various features in the past.

> The information is mostly already there in out.policy_* but has to be linked at the correct places

Where would you expect it to be listed?

**Comment by ilu33** [comment]
I'm not asking for any information I'm personally interested in. I know where to look. I just recommend some changes to comply with the law which - since May 25th - is quite specific about where which information has to be.

The privacy policy has to be linked here:

1. https://cryptpad.fr/register/ 
    mandatory tickbox - I accept the terms of service
    mandatory tickbox - I have read the privacy policy
2. https://cryptpad.fr/settings/ -> Feedback (which needs to be opt-in, I don't remember whether the box was ticked by default)

https://cryptpad.fr/privacy.html also needs several more sections:

1. Who is responsible for delivering the service, adress and contact (this needs to be read from config files because it would depend on who is deploying the service).
2. What we know about you - already there
3. What we store and for how long - to do
4. How we use what we learn - already there
5. What we (don't) tell others about you - already there
6. Links to other sites and third party services - mostly there
7. List of user rights according to Art. 12 ff GDPR (there are lists on the web, most of them are too long and can be shortened)
8. Whatever else you'd like to add

This might be annoying but all in all GDPR is a good thing, even if some of it seems redundant or superfluous.

**Comment by cjdelisle** [comment]
Thank you for your suggestions. As you probably know, this is an open source project and we are only a few people and thus cannot address all of these feature requests immediately. We are seeking funds to help us be able to continue development of CryptPad in 2019 https://opencollective.com/cryptpad and I hope you can understand we are doing our best and that it would be very sad to see an open source privacy-enabling project ended because of the GDPR.

That said, if you would like to raise an official GDPR request with XWiki SAS, the company hosting cryptpad.fr, you can do so by contacting the DPO as per: https://www.xwiki.com/en/company/privacypolicy

**Comment by ilu33** [comment]
Well, I've already provided everything in detail (something I do without payment **because** this is a open source project). There's not much work left: inserting 2 links in the code and some text into a web document.

Open source projects are not exempt from the law, I'm trying to help you to comply. I'm certainly not raising any requests. Sorry I wasted my time.

**Comment by redchrision** [comment]
Hello, ilu33! As my colleagues cjdelisle and ansuz were mentioning, we consider privacy to be one of our priorities and we thank you for your contribution. 

If you have any requests in the future regarding your rights under data protection laws, you can contact us at privacy@xwiki.com, following the information available in the Privacy policy from xwiki.com: https://www.xwiki.com/en/company/privacypolicy. XWiki SAS is the company hosting CryptPad project. 

As the DPO of XWiki, I can personally ensure you that your feedback is valuable for us and that we will consider it in reviewing the information available specific for CryptPad, as we are currently working on this aspect. 

Thank you again for your time and interest dedicated to our Open source project and please do feel free to contact us anytime you wish on privacy matters.

Best regards,
Cristina

**Comment by mthld** [comment]
This has been fixed a while ago, for reference:
- Terms of Service: https://cryptpad.fr/code/#/2/code/view/QpPIuoUAHytCF8JjkunAPqnO7yuu1GWd3OUDwYe5ZA8/present/
- Privacy Policy: https://cryptpad.fr/pad/#/2/pad/view/GcNjAWmK6YDB3EO2IipRZ0fUe89j43Ryqeb4fjkjehE/

![Screenshot 2022-08-05 at 15 07 18](https://user-images.githubusercontent.com/41020854/183083762-5d8c65ac-3106-4b85-b71c-2c528fc5864b.jpg)

**Comment by Aspie96** [comment]
The privacy policy still doesn't mention, for example, the right to lodge a complaint to a supervising authority, something the GDPR expressly requires.

The privacy policy should be designed with the purpose of giving the information required by Article 13 of the GDPR.

**Comment by mthld** [comment]
Updated!

**Comment by Aspie96** [comment]
In regards to the "official checklist" on gdpr.eu, I shall say that gdpr.eu has absolutely nothing "official", other than being merely funded by the EU.

It's simply a website by a specific company: Proton. It's not the text of the law.

The only official thing is the text of the law. There is no checklist and nothing else a privacy policy should be based upon.

This is the official resource that should be using: https://eur-lex.europa.eu/eli/reg/2016/679/oj, not some summary of it (nor my comments, which are not legal advice). In addition to this, of course, the dispositions from privacy authorities.
